In [2]:
import sys
print(sys.executable)

c:\Users\Ferryadmin\Projects\data_science_projects\Electricity_Renewables_Project\env\Scripts\python.exe

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Notebook is working")

Notebook is working

In [4]:
import os

os.chdir("..")
print(os.getcwd())

c:\Users\Ferryadmin\Projects\data_science_projects\Electricity_Renewables_Project

In [5]:
with open("data/interim/electricity_prices.csv", "r", encoding="utf-8", errors="replace") as f:
    for i in range(15):
        print(f.readline())

"Average retail price of electricity"

"https://www.eia.gov/electricity/data/browser/#/topic/7?agg=0,1&geo=fvvvvvvvvvvvo&endsec=6&freq=M&start=200101&end=202601&ctype=linechart&ltype=pin&rtype=s&maptype=0&rse=0&pin="

"Tue Apr 14 2026 18:05:54 GMT-0400 (Bolivia Time)"

"Source: U.S. Energy Information Administration"

"description","units","source key","Jan 2001","Feb 2001","Mar 2001","Apr 2001","May 2001","Jun 2001","Jul 2001","Aug 2001","Sep 2001","Oct 2001","Nov 2001","Dec 2001","Jan 2002","Feb 2002","Mar 2002","Apr 2002","May 2002","Jun 2002","Jul 2002","Aug 2002","Sep 2002","Oct 2002","Nov 2002","Dec 2002","Jan 2003","Feb 2003","Mar 2003","Apr 2003","May 2003","Jun 2003","Jul 2003","Aug 2003","Sep 2003","Oct 2003","Nov 2003","Dec 2003","Jan 2004","Feb 2004","Mar 2004","Apr 2004","May 2004","Jun 2004","Jul 2004","Aug 2004","Sep 2004","Oct 2004","Nov 2004","Dec 2004","Jan 2005","Feb 2005","Mar 2005","Apr 2005","May 2005","Jun 2005","Jul 2005","Aug 2005","Sep 2005","Oct 2005","Nov 2005","Dec 2005","Jan 2006","Feb 2006","Mar 2006","Apr 2006","May 2006","Jun 2006","Jul 2006","Aug 2006","Sep 2006","Oct 2006","Nov 2006","Dec 2006","Jan 2007","Feb 2007","Mar 2007","Apr 2007","May 2007","Jun 2007","Jul 2007","Aug 2007","Sep 2007","Oct 2007","Nov 2007","Dec 2007","Jan 2008","Feb 2008","Mar 2008","Apr 2008","May 2008","Jun 2008","Jul 2008","Aug 2008","Sep 2008","Oct 2008","Nov 2008","Dec 2008","Jan 2009","Feb 2009","Mar 2009","Apr 2009","May 2009","Jun 2009","Jul 2009","Aug 2009","Sep 2009","Oct 2009","Nov 2009","Dec 2009","Jan 2010","Feb 2010","Mar 2010","Apr 2010","May 2010","Jun 2010","Jul 2010","Aug 2010","Sep 2010","Oct 2010","Nov 2010","Dec 2010","Jan 2011","Feb 2011","Mar 2011","Apr 2011","May 2011","Jun 2011","Jul 2011","Aug 2011","Sep 2011","Oct 2011","Nov 2011","Dec 2011","Jan 2012","Feb 2012","Mar 2012","Apr 2012","May 2012","Jun 2012","Jul 2012","Aug 2012","Sep 2012","Oct 2012","Nov 2012","Dec 2012","Jan 2013","Feb 2013","Mar 2013","Apr 2013","May 2013","Jun 2013","Jul 2013","Aug 2013","Sep 2013","Oct 2013","Nov 2013","Dec 2013","Jan 2014","Feb 2014","Mar 2014","Apr 2014","May 2014","Jun 2014","Jul 2014","Aug 2014","Sep 2014","Oct 2014","Nov 2014","Dec 2014","Jan 2015","Feb 2015","Mar 2015","Apr 2015","May 2015","Jun 2015","Jul 2015","Aug 2015","Sep 2015","Oct 2015","Nov 2015","Dec 2015","Jan 2016","Feb 2016","Mar 2016","Apr 2016","May 2016","Jun 2016","Jul 2016","Aug 2016","Sep 2016","Oct 2016","Nov 2016","Dec 2016","Jan 2017","Feb 2017","Mar 2017","Apr 2017","May 2017","Jun 2017","Jul 2017","Aug 2017","Sep 2017","Oct 2017","Nov 2017","Dec 2017","Jan 2018","Feb 2018","Mar 2018","Apr 2018","May 2018","Jun 2018","Jul 2018","Aug 2018","Sep 2018","Oct 2018","Nov 2018","Dec 2018","Jan 2019","Feb 2019","Mar 2019","Apr 2019","May 2019","Jun 2019","Jul 2019","Aug 2019","Sep 2019","Oct 2019","Nov 2019","Dec 2019","Jan 2020","Feb 2020","Mar 2020","Apr 2020","May 2020","Jun 2020","Jul 2020","Aug 2020","Sep 2020","Oct 2020","Nov 2020","Dec 2020","Jan 2021","Feb 2021","Mar 2021","Apr 2021","May 2021","Jun 2021","Jul 2021","Aug 2021","Sep 2021","Oct 2021","Nov 2021","Dec 2021","Jan 2022","Feb 2022","Mar 2022","Apr 2022","May 2022","Jun 2022","Jul 2022","Aug 2022","Sep 2022","Oct 2022","Nov 2022","Dec 2022","Jan 2023","Feb 2023","Mar 2023","Apr 2023","May 2023","Jun 2023","Jul 2023","Aug 2023","Sep 2023","Oct 2023","Nov 2023","Dec 2023","Jan 2024","Feb 2024","Mar 2024","Apr 2024","May 2024","Jun 2024","Jul 2024","Aug 2024","Sep 2024","Oct 2024","Nov 2024","Dec 2024","Jan 2025","Feb 2025","Mar 2025","Apr 2025","May 2025","Jun 2025","Jul 2025","Aug 2025","Sep 2025","Oct 2025","Nov 2025","Dec 2025","Jan 2026"

"Average retail price of electricity","cents per kilowatthour",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

"United States",,"ELEC.PRICE.US-ALL.M",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

"New England",,"ELEC.PRICE.NEW-ALL.M",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

"New England : all sectors",,"ELEC.PRICE.NEW-ALL.M",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

"New England : commercial","cents per kilowatthour","ELEC.PRICE.NEW-COM.M",10.30,10.44,10.54,10.85,10.74,11.33,12.56,9.59,12.40,11.48,10.39,10.67,9.98,9.68,9.36,9.95,9.39,9.90,10.43,9.96,10.30,10.04,9.37,9.69,8.81,9.27,9.79,9.59,10.12,10.83,10.96,11.13,11.40,10.89,10.24,10.60,10.00,10.96,10.04,10.31,10.11,11.20,11.13,11.18,11.14,10.38,10.34,10.41,11.26,11.66,11.37,11.48,11.25,11.97,12.11,12.00,12.87,11.98,12.55,12.61,13.98,15.22,14.55,14.38,14.09,15.05,14.57,15.09,14.99,14.10,13.78,14.31,15.03,15.45,14.60,14.53,14.36,14.74,14.92,14.64,15.15,14.46,14.26,14.35,14.80,14.83,15.02,14.85,16.27,16.18,16.63,16.91,15.90,16.10,15.68,15.84,16.00,15.95,15.04,15.25,15.04,15.43,15.10,14.97,15.22,15.07,14.74,14.68,14.74,14.68,14.83,14.86,14.43,14.83,14.80,15.07,14.94,14.49,14.43,14.44,14.58,14.25,14.21,14.08,14.22,14.68,14.20,14.60,14.62,13.87,14.02,14.23,13.94,13.93,13.81,13.43,13.61,13.73,13.77,13.43,13.70,13.25,13.45,14.11,13.71,14.67,14.39,13.59,13.51,13.82,13.68,13.73,13.73,13.58,13.89,15.36,15.58,15.97,15.55,14.47,13.98,14.37,14.32,14.66,14.37,14.06,14.00,15.00,16.31,17.25,16.90,15.70,15.15,14.98,14.82,14.91,15.03,15.06,14.63,14.89,15.11,15.60,15.33,15.18,14.95,15.16,15.16,15.18,15.47,15.39,14.91,14.70,15.16,15.56,14.98,15.14,14.94,15.60,15.77,15.63,16.01,15.74,15.59,15.55,16.57,17.10,17.06,16.18,16.10,15.89,16.08,16.14,16.89,16.57,16.36,16.67,16.91,16.89,16.93,16.45,16.32,16.34,15.99,16.20,16.11,16.00,15.80,16.11,16.19,16.35,15.98,16.10,15.43,15.33,15.81,16.19,15.72,15.67,15.50,15.62,15.86,16.47,16.23,15.70,15.64,16.07,16.83,16.11,16.95,16.69,16.50,16.90,18.13,19.27,17.87,17.40,16.97,17.75,17.09,18.72,19.05,18.13,18.10,19.13,20.64,21.10,20.13,20.36,18.13,18.94,18.41,18.94,18.85,19.19,19.18,19.63,20.62,20.67,19.99,19.58,19.87,19.78,20.01,20.64,21.07,20.74,21.65,22.10,22.87,23.62,23.10,22.68,22.20,21.94,22.48,22.66,21.79,21.60,22.46,23.53,24.22

"New England : industrial","cents per kilowatthour","ELEC.PRICE.NEW-IND.M",9.04,8.52,8.78,8.37,8.19,8.59,9.00,8.63,8.51,8.24,7.81,8.08,8.12,7.70,7.74,7.61,7.80,8.02,8.36,7.90,8.10,8.03,8.45,8.42,7.76,8.10,8.30,8.18,8.28,8.39,8.56,8.87,8.71,8.27,8.14,8.46,8.17,8.47,8.36,8.16,7.99,8.37,8.32,8.63,8.09,7.73,7.92,8.41,8.89,9.14,8.87,8.44,8.86,9.05,9.06,9.37,9.12,9.17,9.25,10.00,11.08,11.93,11.39,11.51,11.17,11.93,11.71,11.92,11.47,11.35,11.44,12.07,13.34,12.80,13.27,12.38,12.20,12.62,12.83,13.00,12.16,12.68,12.83,12.78,12.93,12.51,12.96,12.86,13.65,13.64,14.32,14.09,13.64,13.59,13.79,13.58,13.63,13.81,13.77,13.27,13.11,13.64,13.55,13.71,13.49,13.20,13.02,13.08,13.01,12.99,12.79,12.74,12.59,13.32,13.43,13.40,13.30,12.51,12.61,12.95,12.78,12.41,12.39,11.96,12.36,13.12,12.76,12.95,12.91,12.12,12.23,12.46,11.77,11.65,11.77,11.39,11.71,12.35,12.17,12.21,12.06,11.43,11.59,11.77,12.01,12.90,12.44,11.78,11.91,12.26,12.71,12.48,12.47,11.64,11.70,12.60,12.80,13.35,13.01,11.64,11.37,11.73,11.83,11.54,11.36,10.90,11.02,11.76,12.53,13.96,13.54,12.09,11.90,12.03,11.86,12.27,12.20,11.84,12.14,11.97,12.23,12.35,12.28,11.99,11.89,11.96,12.41,12.45,12.34,12.07,12.07,12.30,12.57,12.43,12.44,12.28,12.14,12.51,12.82,12.76,12.66,12.32,12.55,12.89,13.74,13.98,13.04,12.97,12.70,13.19,13.12,13.02,13.13,12.91,13.05,13.60,13.43,14.07,13.45,13.19,12.59,13.16,12.77,12.72,12.93,12.51,13.18,13.06,13.21,13.09,12.85,12.87,13.04,12.83,13.09,13.04,12.81,12.52,12.56,12.72,12.42,13.23,12.75,11.91,12.06,12.65,12.86,12.71,13.05,13.08,13.41,13.47,14.91,15.18,14.47,14.38,14.63,15.20,15.35,15.68,15.39,14.57,14.47,16.01,16.60,16.42,16.05,15.19,15.25,15.23,15.83,15.70,15.72,15.77,15.75,16.21,16.79,16.49,15.84,15.70,15.47,15.08,16.32,16.26,16.54,16.56,16.80,17.58,18.28,19.20,17.98,17.15,17.00,17.67,18.10,18.05,17.12,16.27,17.63,18.79,20.30

"Connecticut",,"ELEC.PRICE.CT-ALL.M",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

"Connecticut : all sectors",,"ELEC.PRICE.CT-ALL.M",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

"Connecticut : commercial","cents per kilowatthour","ELEC.PRICE.CT-COM.M",9.19,8.73,8.89,9.15,9.45,9.28,9.29,9.53,9.36,9.53,9.20,9.35,9.13,9.19,9.04,9.57,9.56,9.21,9.71,9.21,9.31,9.43,9.29,9.21,9.16,9.24,9.38,9.64,10.21,10.15,10.16,10.31,10.42,10.50,9.79,9.95,10.05,11.21,9.20,10.39,10.41,10.65,10.43,10.64,9.28,8.86,8.98,8.56,10.65,11.16,11.15,11.10,11.50,11.88,11.75,11.79,11.98,11.78,11.84,11.56,12.27,13.14,13.42,14.30,13.76,14.11,14.10,14.67,14.97,14.15,14.24,15.14,16.08,16.32,15.81,15.36,15.87,15.37,15.40,15.12,15.05,14.95,14.73,14.80,15.74,16.86,15.56,16.48,17.54,16.99,17.75,18.99,17.64,17.58,17.41,16.84,17.27,17.45,16.76,16.79,16.86,16.85,16.73,16.77,16.63,17.07,16.70,16.53,16.53,16.65,16.54,16.66,16.61,16.45,16.55,16.38,16.35,16.35,16.42,15.92,16.08,15.73,15.71,15.70,15.66,15.65,15.49,15.43,15.30,15.22,15.57,15.37,15.00,14.73,14.53,14.76,14.69,14.55,14.59,14.51,14.51,14.73,14.86,14.45,14.55,15.28,14.90,14.58,14.55,14.68,14.36,14.28,14.48,14.63,14.73,14.73,16.50,16.56,16.33,15.55,15.04,15.38,14.65,15.39,15.22,15.12,15.18,15.71,16.72,17.27,17.34,16.43,16.56,15.93,15.01,15.14,15.19,15.84,15.27,15.24,15.40,16.15,16.11,15.72,15.87,16.02,15.57,15.47,15.63,15.95,15.90,15.35,15.57,15.89,15.95,15.73,16.05,16.12,16.25,16.02,16.32,16.73,16.04,16.06,16.89,17.08,16.48,16.60,16.51,16.59,15.79,16.39,17.62,16.78,17.08,17.64,17.27,17.71,17.33,17.64,17.13,17.50,15.94,16.65,15.99,16.28,15.46,16.40,16.63,16.84,16.80,18.49,16.53,16.13,16.49,17.55,15.62,16.38,16.04,15.99,16.25,17.07,16.82,16.73,16.01,16.04,17.33,14.60,17.63,16.66,16.62,16.57,17.65,20.97,16.92,19.12,17.72,18.81,16.31,20.02,19.90,18.05,18.09,19.41,21.31,21.14,20.59,20.99,19.33,19.37,18.20,20.77,19.98,19.90,19.37,19.64,20.34,20.69,20.16,20.59,19.31,19.16,19.97,22.27,23.38,22.91,22.73,23.28,24.50,25.83,25.14,24.37,23.26,21.30,22.86,23.70,21.94,21.58,21.18,22.21,23.16

"Connecticut : industrial","cents per kilowatthour","ELEC.PRICE.CT-IND.M",8.09,7.25,7.53,7.79,7.50,7.48,7.94,7.78,7.62,7.61,7.51,7.57,7.84,7.43,7.50,7.67,7.71,7.74,8.36,7.13,7.61,7.85,7.61,7.70,7.13,7.74,7.59,8.21,7.91,8.07,8.16,8.22,8.50,8.15,8.19,7.88,8.14,8.03,8.28,7.98,8.28,8.48,7.97,8.66,7.45,6.84,7.12,7.25,8.77,9.36,9.27,8.84,9.30,9.68,9.56,9.82,9.60,9.53,9.38,9.58,10.46,11.42,11.08,11.92,10.86,11.54,11.86,12.52,12.18,11.63,12.08,13.00,13.99,13.22,12.78,12.83,12.47,12.64,14.21,12.22,12.29,12.52,13.26,13.05,15.22,13.85,13.73,14.29,14.65,14.82,16.15,15.73,15.17,15.28,15.20,15.17,15.34,15.32,15.19,15.10,14.56,15.31,15.52,14.73,14.74,14.87,14.79,14.31,15.41,15.01,14.84,14.62,14.35,14.78,14.43,14.04,14.43,14.02,14.25,14.04,13.94,13.30,13.41,13.24,12.97,13.28,13.28,12.98,13.09,13.54,12.82,13.19,13.19,12.80,12.63,12.56,12.40,12.54,12.61,12.45,12.87,12.92,12.63,12.57,12.73,12.84,12.71,12.42,12.40,12.60,12.51,12.50,12.63,12.68,12.81,12.53,13.19,14.34,13.64,13.10,12.47,12.74,13.04,12.40,12.49,12.38,12.40,13.02,13.26,14.26,14.26,12.96,12.67,12.77,12.18,12.55,12.64,12.78,12.97,12.39,12.80,13.24,13.19,12.68,12.85,12.55,12.87,12.73,12.81,12.73,12.61,12.73,13.12,12.95,12.96,12.75,13.03,12.84,13.51,13.24,13.29,13.28,13.32,12.85,14.92,13.88,13.80,13.59,12.38,14.85,13.37,13.78,14.00,13.54,13.82,13.99,14.25,14.06,13.61,13.81,12.98,13.60,13.17,13.24,13.24,13.01,13.05,13.29,13.82,13.39,13.15,13.18,13.91,12.61,13.37,13.33,13.08,12.29,12.59,12.32,9.93,10.52,11.49,7.79,9.07,9.63,9.75,8.68,9.82,9.89,9.58,9.67,14.79,15.75,14.42,14.76,14.43,15.20,14.98,15.91,15.44,14.39,14.48,16.55,16.86,16.23,15.78,15.46,14.61,14.50,15.66,15.90,16.08,15.95,15.22,16.28,16.67,17.28,15.98,15.93,15.42,15.29,17.00,17.49,19.56,17.44,17.97,19.69,19.96,21.17,19.62,18.88,17.28,19.03,18.59,18.84,17.99,12.94,17.70,19.13,21.13

In [6]:
import pandas as pd

df = pd.read_csv("data/interim/electricity_prices.csv", skiprows=4)

print(df.head(10))
print(df.columns)
print(df.shape)

                           description                   units  \
0  Average retail price of electricity  cents per kilowatthour
1                        United States                     NaN
2                          New England                     NaN
3            New England : all sectors                     NaN
4             New England : commercial  cents per kilowatthour
5             New England : industrial  cents per kilowatthour
6                          Connecticut                     NaN
7            Connecticut : all sectors                     NaN
8             Connecticut : commercial  cents per kilowatthour
9             Connecticut : industrial  cents per kilowatthour

             source key  Jan 2001  Feb 2001  Mar 2001  Apr 2001  May 2001  \
0                   NaN       NaN       NaN       NaN       NaN       NaN
1   ELEC.PRICE.US-ALL.M       NaN       NaN       NaN       NaN       NaN
2  ELEC.PRICE.NEW-ALL.M       NaN       NaN       NaN       NaN       NaN
3  ELEC.PRICE.NEW-ALL.M       NaN       NaN       NaN       NaN       NaN
4  ELEC.PRICE.NEW-COM.M     10.30     10.44     10.54     10.85     10.74
5  ELEC.PRICE.NEW-IND.M      9.04      8.52      8.78      8.37      8.19
6   ELEC.PRICE.CT-ALL.M       NaN       NaN       NaN       NaN       NaN
7   ELEC.PRICE.CT-ALL.M       NaN       NaN       NaN       NaN       NaN
8   ELEC.PRICE.CT-COM.M      9.19      8.73      8.89      9.15      9.45
9   ELEC.PRICE.CT-IND.M      8.09      7.25      7.53      7.79      7.50

   Jun 2001  Jul 2001  ...  Apr 2025  May 2025  Jun 2025  Jul 2025  Aug 2025  \
0       NaN       NaN  ...       NaN       NaN       NaN       NaN       NaN
1       NaN       NaN  ...       NaN       NaN       NaN       NaN       NaN
2       NaN       NaN  ...       NaN       NaN       NaN       NaN       NaN
3       NaN       NaN  ...       NaN       NaN       NaN       NaN       NaN
4     11.33     12.56  ...     22.68     22.20     21.94     22.48     22.66
5      8.59      9.00  ...     17.15     17.00     17.67     18.10     18.05
6       NaN       NaN  ...       NaN       NaN       NaN       NaN       NaN
7       NaN       NaN  ...       NaN       NaN       NaN       NaN       NaN
8      9.28      9.29  ...     24.37     23.26     21.30     22.86     23.70
9      7.48      7.94  ...     18.88     17.28     19.03     18.59     18.84

   Sep 2025  Oct 2025  Nov 2025  Dec 2025  Jan 2026
0       NaN       NaN       NaN       NaN       NaN
1       NaN       NaN       NaN       NaN       NaN
2       NaN       NaN       NaN       NaN       NaN
3       NaN       NaN       NaN       NaN       NaN
4     21.79     21.60     22.46     23.53     24.22
5     17.12     16.27     17.63     18.79     20.30
6       NaN       NaN       NaN       NaN       NaN
7       NaN       NaN       NaN       NaN       NaN
8     21.94     21.58     21.18     22.21     23.16
9     17.99     12.94     17.70     19.13     21.13

[10 rows x 304 columns]
Index(['description', 'units', 'source key', 'Jan 2001', 'Feb 2001',
       'Mar 2001', 'Apr 2001', 'May 2001', 'Jun 2001', 'Jul 2001',
       ...
       'Apr 2025', 'May 2025', 'Jun 2025', 'Jul 2025', 'Aug 2025', 'Sep 2025',
       'Oct 2025', 'Nov 2025', 'Dec 2025', 'Jan 2026'],
      dtype='str', length=304)
(246, 304)

In [7]:
df_clean = df[df["description"].str.contains(": commercial|: industrial", na=False)].copy()

df_clean[["description"]].head(10)

                   description
4     New England : commercial
5     New England : industrial
8     Connecticut : commercial
9     Connecticut : industrial
12          Maine : commercial
13          Maine : industrial
16  Massachusetts : commercial
17  Massachusetts : industrial
20  New Hampshire : commercial
21  New Hampshire : industrial

In [8]:
df_clean[["state_or_region", "sector"]] = df_clean["description"].str.split(" : ", expand=True)

df_clean[["state_or_region", "sector"]].head()

   state_or_region      sector
4      New England  commercial
5      New England  industrial
8      Connecticut  commercial
9      Connecticut  industrial
12           Maine  commercial

In [9]:
month_columns = df_clean.columns[3:]

df_long = df_clean.melt(
    id_vars=["state_or_region", "sector"],
    value_vars=month_columns,
    var_name="date",
    value_name="price"
)

df_long.head()

  state_or_region      sector      date  price
0     New England  commercial  Jan 2001  10.30
1     New England  industrial  Jan 2001   9.04
2     Connecticut  commercial  Jan 2001   9.19
3     Connecticut  industrial  Jan 2001   8.09
4           Maine  commercial  Jan 2001  10.33

In [ ]:
#Converting monthly date format to yearly
month_columns = df_clean.columns[3:]

df_long = df_clean.melt(
    id_vars=["state_or_region", "sector"],
    value_vars=month_columns,
    var_name="date",
    value_name="price"
)

df_long["date"] = pd.to_datetime(df_long["date"], format="%b %Y")
df_long["price"] = pd.to_numeric(df_long["price"], errors="coerce")

In [28]:
#aggregates monthly values to yearly by mean
df_long["year"] = df_long["date"].dt.year

prices_annual = (
    df_long
    .groupby(["state_or_region", "sector", "year"], as_index=False)["price"]
    .mean()
)

prices_annual.head()

  state_or_region      sector  year     price
0         Alabama  commercial  2001  6.549167
1         Alabama  commercial  2002  6.635833
2         Alabama  commercial  2003  6.855000
3         Alabama  commercial  2004  7.118333
4         Alabama  commercial  2005  7.475833

In [29]:
df_long = df_long.dropna(subset=["price"])

In [33]:
print(prices_annual.head(10))
print(prices_annual.shape)
print(prices_annual.dtypes)

  state_or_region      sector  year      price
0         Alabama  commercial  2001   6.549167
1         Alabama  commercial  2002   6.635833
2         Alabama  commercial  2003   6.855000
3         Alabama  commercial  2004   7.118333
4         Alabama  commercial  2005   7.475833
5         Alabama  commercial  2006   8.133333
6         Alabama  commercial  2007   8.685000
7         Alabama  commercial  2008   9.828333
8         Alabama  commercial  2009  10.047500
9         Alabama  commercial  2010  10.176667
(3172, 4)
state_or_region        str
sector                 str
year                 int32
price              float64
dtype: object

  state_or_region      sector  year     price
0         Alabama  commercial  2001  6.549167
1         Alabama  commercial  2002  6.635833
2         Alabama  commercial  2003  6.855000
3         Alabama  commercial  2004  7.118333
4         Alabama  commercial  2005  7.475833
(3172, 4)

In [36]:
regions = [
    "United States",
    "New England",
    "Middle Atlantic",
    "East North Central",
    "West North Central",
    "South Atlantic",
    "East South Central",
    "West South Central",
    "Mountain",
    "Pacific",
    "Contiguous 48 States",
    "U.S. Total"
]

df_state = prices_annual[~prices_annual["state_or_region"].isin(regions)].copy()
df_region = prices_annual[prices_annual["state_or_region"].isin(regions)].copy()

In [37]:
print(df_state["state_or_region"].unique()[:20])
print(df_region["state_or_region"].unique())

<StringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District Of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine']
Length: 20, dtype: str
<StringArray>
['East North Central', 'East South Central',    'Middle Atlantic',
           'Mountain',        'New England',     'South Atlantic',
 'West North Central', 'West South Central']
Length: 8, dtype: str

In [38]:
df_state.to_csv("data/processed/electricity_prices_states.csv", index=False)
df_region.to_csv("data/processed/electricity_prices_regions.csv", index=False)