In [12]:
with open("../data/interim/Net_renewables_generation.csv", "r", encoding="utf-8", errors="replace") as f:
    for i in range(15):
        print(f.readline())

"Net generation for other renewables"

"https://www.eia.gov/electricity/data/browser/#/topic/0?agg=1,0,2&fuel=02&geo=vvvvvvvvvvvvo&sec=o3g&linechart=ELEC.GEN.AOR-US-99.A~ELEC.GEN.AOR-US-1.A~ELEC.GEN.AOR-US-94.A~ELEC.GEN.AOR-US-96.A~ELEC.GEN.AOR-US-97.A&columnchart=ELEC.GEN.AOR-US-99.A~ELEC.GEN.AOR-US-1.A~ELEC.GEN.AOR-US-94.A~ELEC.GEN.AOR-US-96.A~ELEC.GEN.AOR-US-97.A&map=ELEC.GEN.AOR-US-99.A&freq=A&ctype=linechart&ltype=pin&rtype=s&pin=&rse=0&maptype=0"

"Thu Apr 16 2026 19:22:11 GMT-0400 (Bolivia Time)"

"Source: U.S. Energy Information Administration"

"description","units","source key","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","2023","2024","2025"

"Net generation for other renewables","thousand megawatthours",,,,,,,,,,,,,,,,,,,,,,,,,,

"United States","thousand megawatthours","ELEC.GEN.AOR-US-99.A",,,,,,,,,,,,,,,,,,,,,,,,,

"United States : all sectors","thousand megawatthours","ELEC.GEN.AOR-US-99.A",70769,79109,79487,83067,87329,96525,105238,126101,144279,167173,193981,218333,253508,279213,295161,341633,386250,414292,440799,497738,563682,646025,650239,733567,821918

"United States : electric power",,"ELEC.GEN.AOR-US-98.A",,,,,,,,,,,,,,,,,,,,,,,,,

"United States : electric utility","thousand megawatthours","ELEC.GEN.AOR-US-1.A",1666,3089,3421,3692,4945,6588,8953,11308,14617,17927,21933,28017,32417,34496,37485,42661,46111,49100,55188,69742,89249,103925,106543,123555,136918

"United States : independent power producers","thousand megawatthours","ELEC.GEN.AOR-US-94.A",40593,44466,46060,48636,51708,59345,65751,85776,101860,120956,141954,160064,189045,212809,225820,267056,308338,333491,354823,398200,445396,512744,516694,582350,656870

"United States : all commercial","thousand megawatthours","ELEC.GEN.AOR-US-96.A",1025,1065,1302,1575,1673,1619,1614,1555,1769,1714,2476,2545,2956,3232,3220,3226,3251,3214,3426,3347,3576,4854,4545,4441,4484

"United States : all industrial","thousand megawatthours","ELEC.GEN.AOR-US-97.A",27485,30489,28704,29164,29003,28972,28919,27462,26033,26576,27619,27707,29091,28675,28635,28690,28550,28487,27361,26449,25461,24502,22456,23220,23646

"New England","thousand megawatthours","ELEC.GEN.AOR-NEW-99.A",,,,,,,,,,,,,,,,,,,,,,,,,

"New England : all sectors","thousand megawatthours","ELEC.GEN.AOR-NEW-99.A",7559,7466,6928,6975,7444,7355,7919,7806,7698,8020,8015,8557,9487,9957,10208,10574,11308,11398,11095,11206,11583,12151,11419,12351,14591

In [13]:
import pandas as pd

df = pd.read_csv("../data/interim/Net_renewables_generation.csv", skiprows=4)


df.columns
df.shape

(435, 28)

In [14]:
df.head(10)

,description,units,source key,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Net generation for other renewables,thousand megawatthours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,United States,thousand megawatthours,ELEC.GEN.AOR-US-99.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,United States : all sectors,thousand megawatthours,ELEC.GEN.AOR-US-99.A,70769,79109,79487,83067,87329,96525,105238,...,341633,386250,414292,440799,497738,563682,646025,650239,733567,821918
3,United States : electric power,NaN,ELEC.GEN.AOR-US-98.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States : electric utility,thousand megawatthours,ELEC.GEN.AOR-US-1.A,1666,3089,3421,3692,4945,6588,8953,...,42661,46111,49100,55188,69742,89249,103925,106543,123555,136918
5,United States : independent power producers,thousand megawatthours,ELEC.GEN.AOR-US-94.A,40593,44466,46060,48636,51708,59345,65751,...,267056,308338,333491,354823,398200,445396,512744,516694,582350,656870
6,United States : all commercial,thousand megawatthours,ELEC.GEN.AOR-US-96.A,1025,1065,1302,1575,1673,1619,1614,...,3226,3251,3214,3426,3347,3576,4854,4545,4441,4484
7,United States : all industrial,thousand megawatthours,ELEC.GEN.AOR-US-97.A,27485,30489,28704,29164,29003,28972,28919,...,28690,28550,28487,27361,26449,25461,24502,22456,23220,23646
8,New England,thousand megawatthours,ELEC.GEN.AOR-NEW-99.A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,New England : all sectors,thousand megawatthours,ELEC.GEN.AOR-NEW-99.A,7559,7466,6928,6975,7444,7355,7919,...,10574,11308,11398,11095,11206,11583,12151,11419,12351,14591

In [15]:
df = pd.read_csv("../data/interim/Net_renewables_generation.csv", skiprows=4)

df.head()
df.columns
df.shape

(435, 28)

In [16]:
print(df.head(20).to_string())
print(df.columns.tolist())
print(df.iloc[:30, 0].tolist())

                                    description                   units             source key   2001   2002   2003   2004   2005   2006    2007    2008    2009    2010    2011    2012    2013    2014    2015    2016    2017    2018    2019    2020    2021    2022    2023    2024    2025
0           Net generation for other renewables  thousand megawatthours                    NaN    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1                                 United States  thousand megawatthours   ELEC.GEN.AOR-US-99.A    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2                   United States : all sectors  thousand megawatthours   ELEC.GEN.AOR-US-99.A  70769  79109  79487  83067  87329  96525  105238  126101  144279  167173  193981  218333  253508  279213  295161  341633  386250  414292  440799  497738  563682  646025  650239  733567  821918
3                United States : electric power                     NaN   ELEC.GEN.AOR-US-98.A    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4              United States : electric utility  thousand megawatthours    ELEC.GEN.AOR-US-1.A   1666   3089   3421   3692   4945   6588    8953   11308   14617   17927   21933   28017   32417   34496   37485   42661   46111   49100   55188   69742   89249  103925  106543  123555  136918
5   United States : independent power producers  thousand megawatthours   ELEC.GEN.AOR-US-94.A  40593  44466  46060  48636  51708  59345   65751   85776  101860  120956  141954  160064  189045  212809  225820  267056  308338  333491  354823  398200  445396  512744  516694  582350  656870
6                United States : all commercial  thousand megawatthours   ELEC.GEN.AOR-US-96.A   1025   1065   1302   1575   1673   1619    1614    1555    1769    1714    2476    2545    2956    3232    3220    3226    3251    3214    3426    3347    3576    4854    4545    4441    4484
7                United States : all industrial  thousand megawatthours   ELEC.GEN.AOR-US-97.A  27485  30489  28704  29164  29003  28972   28919   27462   26033   26576   27619   27707   29091   28675   28635   28690   28550   28487   27361   26449   25461   24502   22456   23220   23646
8                                   New England  thousand megawatthours  ELEC.GEN.AOR-NEW-99.A    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9                     New England : all sectors  thousand megawatthours  ELEC.GEN.AOR-NEW-99.A   7559   7466   6928   6975   7444   7355    7919    7806    7698    8020    8015    8557    9487    9957   10208   10574   11308   11398   11095   11206   11583   12151   11419   12351   14591
10                 New England : electric power                     NaN  ELEC.GEN.AOR-NEW-98.A    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
11               New England : electric utility  thousand megawatthours   ELEC.GEN.AOR-NEW-1.A    273    187    234    227    245    329     610     647     553     641     574     664     869     883     890     872     858     787     830     712     686     678     572     588     653
12    New England : independent power producers  thousand megawatthours  ELEC.GEN.AOR-NEW-94.A   5146   4832   4727   4628   4993   5009    5211    5125    5370    5701    5352    5652    6282    7203    7900    8437    9214    9322    8935    9425    9973   10113    9692   10577   12760
13                 New England : all commercial  thousand megawatthours  ELEC.GEN.AOR-NEW-96.A    127    125    123    110    122    122     123     100     106     102     104     136     175     193     168     187     205     179     155     142     137     575     528     513     499
14                 New England : all industrial  thousand megawatthours  ELEC.GEN.AOR-NEW-97.A   2013   2322   1844   2010   2083   1895    1975    1933    1669    1577    1985    2105    2160    1678    1249    1077    1032    1110    1175     927     786     785     627     673     678
15                                  Connecticut  thousand megawatthours   ELEC.GEN.AOR-CT-99.A    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
16                    Connecticut : all sectors  thousand megawatthours   ELEC.GEN.AOR-CT-99.A    909    821    786    758    753    763     730     734     759     740     660     667     652     769     805     893     845     873     900    1008    1035     940    1022    1038    1361
17                 Connecticut : electric power                     NaN   ELEC.GEN.AOR-CT-98.A    NaN    NaN    NaN    NaN    NaN    NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
18               Connecticut : electric utility  thousand megawatthours    ELEC.GEN.AOR-CT-1.A     84     --     --     --     --     --      --       0      --      --      --      --      --       0       0       3       3       3       3       3       2       1       0       2       3
19    Connecticut : independent power producers  thousand megawatthours   ELEC.GEN.AOR-CT-94.A    825    821    786    758    753    763     730     734     759     740     660     667     626     748     801     891     841     869     892    1000    1029     933    1012    1030    1333
['description', 'units', 'source key', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
['Net generation for other renewables', 'United States', 'United States : all sectors', 'United States : electric power', 'United States : electric utility', 'United States : independent power producers', 'United States : all commercial', 'United States : all industrial', 'New England', 'New England : all sectors', 'New England : electric power', 'New England : electric utility', 'New England : independent power producers', 'New England : all commercial', 'New England : all industrial', 'Connecticut', 'Connecticut : all sectors', 'Connecticut : electric power', 'Connecticut : electric utility', 'Connecticut : independent power producers', 'Connecticut : all commercial', 'Connecticut : all industrial', 'Maine', 'Maine : all sectors', 'Maine : electric power', 'Maine : electric utility', 'Maine : independent power producers', 'Maine : all commercial', 'Maine : all industrial', 'Massachusetts']

In [17]:
df_clean = df[df["description"].str.contains(": all commercial|: all industrial", na=False)].copy()

df_clean[["description"]].head(10)

                       description
6   United States : all commercial
7   United States : all industrial
13    New England : all commercial
14    New England : all industrial
20    Connecticut : all commercial
21    Connecticut : all industrial
27          Maine : all commercial
28          Maine : all industrial
34  Massachusetts : all commercial
35  Massachusetts : all industrial

In [18]:
df_clean = df[df["description"].str.contains(": all commercial|: all industrial", na=False)].copy()

# split description into geography and sector
df_clean[["state_or_region", "sector"]] = df_clean["description"].str.split(" : ", expand=True)

# make sector labels consistent with your other dataset
df_clean["sector"] = df_clean["sector"].str.replace("all ", "", regex=False)

df_clean[["state_or_region", "sector"]].head(10)

   state_or_region      sector
6    United States  commercial
7    United States  industrial
13     New England  commercial
14     New England  industrial
20     Connecticut  commercial
21     Connecticut  industrial
27           Maine  commercial
28           Maine  industrial
34   Massachusetts  commercial
35   Massachusetts  industrial

In [19]:
import pandas as pd

df = pd.read_csv("../data/interim/Net_renewables_generation.csv", skiprows=4)

# Keep only the rows you want
df_clean = df[df["description"].str.contains(r": all commercial|: all industrial", na=False)].copy()

# Split description into two join fields
df_clean[["state_or_region", "sector"]] = df_clean["description"].str.split(" : ", expand=True)

# Make sector names match the prices file
df_clean["sector"] = df_clean["sector"].str.replace("all ", "", regex=False)

# Rename source key for convenience
df_clean = df_clean.rename(columns={"source key": "source_key"})

# Drop regions/national rows if your prices file is state-only
regions_to_drop = [
    "United States",
    "New England",
    "Middle Atlantic",
    "East North Central",
    "West North Central",
    "South Atlantic",
    "East South Central",
    "West South Central",
    "Mountain",
    "Pacific Contiguous",
    "Pacific Noncontiguous"
]

df_clean = df_clean[~df_clean["state_or_region"].isin(regions_to_drop)].copy()

# Find year columns
year_cols = [c for c in df_clean.columns if c.isdigit()]


# Reshape to long
renewables_long = df_clean.melt(
    id_vars=["state_or_region", "sector", "units", "source_key"],
    value_vars=year_cols,
    var_name="year",
    value_name="renewable_generation"
)

# Clean values
renewables_long["renewable_generation"] = renewables_long["renewable_generation"].replace("--", pd.NA)
renewables_long["renewable_generation"] = pd.to_numeric(
    renewables_long["renewable_generation"], errors="coerce"
)

# Make sure year is numeric
renewables_long["year"] = renewables_long["year"].astype(int)

# Drop empty rows
renewables_long = renewables_long.dropna(subset=["renewable_generation"]).copy()

# Final column order
renewables_long = renewables_long[
    ["state_or_region", "sector", "year", "renewable_generation", "units", "source_key"]
].sort_values(["state_or_region", "sector", "year"]).reset_index(drop=True)

print(renewables_long.head())
print(renewables_long.shape)
print(renewables_long.dtypes)

  state_or_region      sector  year  renewable_generation  \
0         Alabama  industrial  2001                3972.0
1         Alabama  industrial  2002                3537.0
2         Alabama  industrial  2003                3491.0
3         Alabama  industrial  2004                3596.0
4         Alabama  industrial  2005                3445.0

                    units            source_key
0  thousand megawatthours  ELEC.GEN.AOR-AL-97.A
1  thousand megawatthours  ELEC.GEN.AOR-AL-97.A
2  thousand megawatthours  ELEC.GEN.AOR-AL-97.A
3  thousand megawatthours  ELEC.GEN.AOR-AL-97.A
4  thousand megawatthours  ELEC.GEN.AOR-AL-97.A
(1755, 6)
state_or_region             str
sector                      str
year                      int64
renewable_generation    float64
units                       str
source_key                  str
dtype: object

In [20]:
renewables_long.to_csv("../data/processed/renewables_clean.csv", index=False)